### ISSUE TITLE
No distorter passed to the CTCTrainer

### ISSUE THREAD

**Issue by matthiasanderer** [jpuigcerver/imgdistort#3]
I am having trouble to get the model running - somehow the Image Distorter cannot be found....
being a bit lost how to solve this I would be glad to get some ideas.

Thank you a lot!

Matthias

-----

laia-train-ctc   --use_distortions true   --batch_size 16   --progress_table_output train_htr.dat   --early_stop_epochs 50   --learning_rate 0.00027   --log_also_to_stderr info   --log_level info   --log_file train_htr.log   model_htr.t7 data/htr/lang/char/symbs.txt   data/htr/tr.lst data/htr/lang/char/tr.txt    data/htr/va.lst data/htr/lang/char/va.txt;
[2017-05-20 18:04:59  WARN] .../matthias/torch/install/share/lua/5.1/laia/util/base.lua:39: Optional lua module "laia.ImageDistorter" was not found!
[2017-05-20 18:04:59  WARN] ...install/lib/luarocks/rocks/laia/scm-1/bin/laia-train-ctc:145: Some layers in cuDNN are non-deterministic on the backward pass. If 100% reproducible experiments are required, use --cudnn_force_convert=false.
[2017-05-20 18:04:59  INFO] ...matthias/torch/install/share/lua/5.1/laia/CTCTrainer.lua:84: CTCTrainer uses the weight regularizer:
laia.WeightDecayRegularizer {
  weight_l2_decay = 0
  weight_l1_decay = 0
}
[2017-05-20 18:04:59  INFO] ...matthias/torch/install/share/lua/5.1/laia/CTCTrainer.lua:74: CTCTrainer uses the adversarial regularizer:
laia.AdversarialRegularizer {
  adversarial_weight = 0
  adversarial_epsilon = 0.0019607843137255
}
[2017-05-20 18:04:59 FATAL] ...matthias/torch/install/share/lua/5.1/laia/CTCTrainer.lua:176: No distorter passed to the CTCTrainer, but --use_distortions=true

stack traceback:
	...matthias/torch/install/share/lua/5.1/laia/CTCTrainer.lua:176: in function 'start'
	...install/lib/luarocks/rocks/laia/scm-1/bin/laia-train-ctc:184: in main chunk
	[C]: at 0x561d27710470

**Comment by jpuigcerver** [comment]
Hi,

Did you successfully install imgdistort and the Torch bindings? You should be able to install it typing:

```
luarocks install https://raw.githubusercontent.com/jpuigcerver/imgdistort/master/torch/imgdistort-scm-1.rockspec
```

If you already executed this command, please, do it again and copy and paste the output here.

**Comment by matthiasanderer** [comment]
Hi Joan,

I did before and do so again - no errors observed by me - find attached the command line

Best Matthias

----

luarocks install https://raw.githubusercontent.com/jpuigcerver/imgdistort/master/torch/imgdistort-scm-1.rockspec
Using https://raw.githubusercontent.com/jpuigcerver/imgdistort/master/torch/imgdistort-scm-1.rockspec... switching to 'build' mode
Cloning into 'imgdistort'...
remote: Counting objects: 26, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 26 (delta 2), reused 16 (delta 2), pack-reused 0
Receiving objects: 100% (26/26), 15.32 KiB | 0 bytes/s, done.
Resolving deltas: 100% (2/2), done.
-- The CXX compiler identification is GNU 4.9.4
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-8.0 (found version "8.0") 
-- Found GLOG: /usr/include  
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find GMock (missing:  GMOCK_LIBRARY GMOCK_INCLUDE_DIR GMOCK_MAIN_LIBRARY) 
-- TORCH_ROOT = /home/matthias/torch/install
-- Found TORCH: /home/matthias/torch/install  
-- Found Torch7 installed in /home/matthias/torch/install
-- Building Torch bindings
-- Missing GMock or GTest, tests will not be compiled!
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    WITH_LUAROCKS


-- Build files have been written to: /tmp/luarocks_imgdistort-scm-1-6988/imgdistort/build.luarocks
[ 16%] Building NVCC (Device) object CMakeFiles/affine.dir/affine_generated_affine.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
Scanning dependencies of target affine
[ 33%] Linking CXX static library libaffine.a
[ 33%] Built target affine
[ 50%] Building NVCC (Device) object CMakeFiles/morphology.dir/morphology_generated_morphology.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
Scanning dependencies of target morphology
[ 66%] Linking CXX static library libmorphology.a
[ 66%] Built target morphology
Scanning dependencies of target imgdistort
[ 83%] Building CXX object torch/CMakeFiles/imgdistort.dir/binding.cc.o
[100%] Linking CXX shared module libimgdistort.so
[100%] Built target imgdistort
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find GMock (missing:  GMOCK_LIBRARY GMOCK_INCLUDE_DIR GMOCK_MAIN_LIBRARY) 
-- TORCH_ROOT = /home/matthias/torch/install
-- Found Torch7 installed in /home/matthias/torch/install
-- Building Torch bindings
-- Missing GMock or GTest, tests will not be compiled!
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_imgdistort-scm-1-6988/imgdistort/build.luarocks
[ 16%] Linking CXX static library libaffine.a
[ 33%] Built target affine
[ 50%] Linking CXX static library libmorphology.a
[ 66%] Built target morphology
[ 83%] Linking CXX shared module libimgdistort.so
[100%] Built target imgdistort
Install the project...
-- Install configuration: "RELEASE"
-- Installing: /home/matthias/torch/install/lib/luarocks/rocks/imgdistort/scm-1/lib/libimgdistort.so
-- Set runtime path of "/home/matthias/torch/install/lib/luarocks/rocks/imgdistort/scm-1/lib/libimgdistort.so" to ""
-- Installing: /home/matthias/torch/install/lib/luarocks/rocks/imgdistort/scm-1/lua/imgdistort/init.lua
Updating manifest for /home/matthias/torch/install/lib/luarocks/rocks
imgdistort scm-1 is now built and installed in /home/matthias/torch/install/ (license: MIT)

**Comment by jpuigcerver** [comment]
Hi Matthias,

That is strange. Most likely, you don't have the Lua environment variables set correctly.

Make sure that your LUA_CPATH environment variable contains something like /home/matthias/torch/install/lib/lua/5.1/?.so

For instance, here is my own definition of this variable:

```bash
export LUA_CPATH='/home/jpuigcerver/.luarocks/lib/lua/5.1/?.so;/opt/torch/install/lib/lua/5.1/?.so;./?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so'
```

That variable should be automatically set by the /home/matthias/torch/install/bin/torch-activate script. My recommendation is that in the .bashrc file in your home, you add the following line at the end:

```bash
source /home/matthias/torch/install/bin/torch-activate
```

Once you have made this updates, make sure to open a new session to update the LUA_CPATH variable.

Let me know if this does not solve your problem.

**Comment by matthiasanderer** [comment]
My LUA_CPATH is as follows: (already hat the torch-activate part in my bashrc)

echo $LUA_CPATH 
/home/matthias/torch/install/lib/?.so;/home/matthias/.luarocks/lib/lua/5.1/?.so;/home/matthias/torch/install/lib/lua/5.1/?.so;./?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so

---
Could there be a problem with the gcc version - I have switched it to 4.9 via update-alternatives... ?

I am really lost here :-(

Best and thank you for your help

Matthias

**Comment by matthiasanderer** [comment]
The problem was rooted in the gcc version.

I changed the gcc version to gcc-5 (via update-alternatives), removed the imgdistort and the laia packages via luarocks and reinstalled them via the given links (
1) luarocks install https://raw.githubusercontent.com/jpuigcerver/imgdistort/master/torch/imgdistort-scm-1.rockspec
2) luarocks install https://raw.githubusercontent.com/jpuigcerver/Laia/master/rocks/laia-scm-1.rockspec

Now the training is running and I hope the problem is solved.

**Comment by jpuigcerver** [comment]
Thanks for letting me know!

**Comment by miliadis** [comment]
Hi, 

thanks for the great library! I have the same issue...I build imgdistort successfully:

luarocks install https://raw.githubusercontent.com/jpuigcerver/imgdistort/master/torch/imgdistort-scm-1.rockspec
Using https://raw.githubusercontent.com/jpuigcerver/imgdistort/master/torch/imgdistort-scm-1.rockspec... switching to 'build' mode
Cloning into 'imgdistort'...
remote: Counting objects: 26, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 26 (delta 2), reused 16 (delta 2), pack-reused 0
Receiving objects: 100% (26/26), 15.69 KiB | 15.69 MiB/s, done.
Resolving deltas: 100% (2/2), done.
-- The CXX compiler identification is GNU 7.0.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "9.0") 
-- Found GLOG: /usr/local/include  
-- Found GTest: /usr/local/lib/libgtest.a  
-- Could NOT find GMock (missing:  GMOCK_LIBRARY GMOCK_MAIN_LIBRARY) 
-- TORCH_ROOT = /home/ubuntu/torch/install
-- Found TORCH: /home/ubuntu/torch/install  
-- Found Torch7 installed in /home/ubuntu/torch/install
-- Building Torch bindings
-- Missing GMock or GTest, tests will not be compiled!
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    WITH_LUAROCKS


-- Build files have been written to: /tmp/luarocks_imgdistort-scm-1-1445/imgdistort/build.luarocks
[ 16%] Building NVCC (Device) object CMakeFiles/morphology.dir/morphology_generated_morphology.cu.o
Scanning dependencies of target morphology
[ 33%] Linking CXX static library libmorphology.a
[ 33%] Built target morphology
[ 50%] Building NVCC (Device) object CMakeFiles/affine.dir/affine_generated_affine.cu.o
Scanning dependencies of target affine
[ 66%] Linking CXX static library libaffine.a
[ 66%] Built target affine
Scanning dependencies of target imgdistort
[ 83%] Building CXX object torch/CMakeFiles/imgdistort.dir/binding.cc.o
[100%] Linking CXX shared module libimgdistort.so
[100%] Built target imgdistort
-- Could NOT find GMock (missing:  GMOCK_LIBRARY GMOCK_MAIN_LIBRARY) 
-- TORCH_ROOT = /home/ubuntu/torch/install
-- Found Torch7 installed in /home/ubuntu/torch/install
-- Building Torch bindings
-- Missing GMock or GTest, tests will not be compiled!
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_imgdistort-scm-1-1445/imgdistort/build.luarocks
[ 16%] Linking CXX static library libmorphology.a
[ 33%] Built target morphology
[ 50%] Linking CXX static library libaffine.a
[ 66%] Built target affine
[ 83%] Linking CXX shared module libimgdistort.so
[100%] Built target imgdistort
Install the project...
-- Install configuration: "RELEASE"
-- Installing: /home/ubuntu/torch/install/lib/luarocks/rocks/imgdistort/scm-1/lib/libimgdistort.so
-- Set runtime path of "/home/ubuntu/torch/install/lib/luarocks/rocks/imgdistort/scm-1/lib/libimgdistort.so" to ""
-- Installing: /home/ubuntu/torch/install/lib/luarocks/rocks/imgdistort/scm-1/lua/imgdistort/init.lua
Updating manifest for /home/ubuntu/torch/install/lib/luarocks/rocks
imgdistort scm-1 is now built and installed in /home/ubuntu/torch/install/ (license: MIT)

but then, when I do th require 'imgdistort' I am getting the error:

th> require 'imgdistort'
/home/ubuntu/torch/install/share/lua/5.1/trepl/init.lua:389: /home/ubuntu/torch/install/share/lua/5.1/trepl/init.lua:389: ...e/ubuntu/torch/install/share/lua/5.1/luarocks/loader.lua:117: error loading module 'libimgdistort' from file '/home/ubuntu/torch/install/lib/lua/5.1/libimgdistort.so':
	/home/ubuntu/torch/install/lib/lua/5.1/libimgdistort.so: undefined symbol: _ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev
stack traceback:
	[C]: in function 'error'
	/home/ubuntu/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	[string "_RESULT={require 'imgdistort'}"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/ubuntu/torch/install/share/lua/5.1/trepl/init.lua:661: in function 'repl'
	...untu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:204: in main chunk
	[C]: at 0x5578499c7470	

I also downgraded to gcc and g++ 5 , but same issue

**Comment by jpuigcerver** [comment]
Hi @miliadis,

I think the problem has something to do with the linking with the Google Log library. It seems to me that when you compiled imgdistort you were compiling it against the libglog version installed in /usr/local/include/glog, but when trying to load the libimgdistort.so, a different version of libglog is being used.

This typically happens when you have two different versions of the library (libglog) installed in different locations. Make sure that the version that the libglog version you are compiling against is the same being loaded.

**Comment by miliadis** [comment]
hey @jpuigcerver thanks for your prompt reply. I 've just removed the build folder and did again  luarocks make torch/imgdistort-scm-1.rockspec and MAGICALLY!! worked! 

Make sure that you delete "build" folder before you re-build your package. Not 100% sure if that made it to work cause I made few other re-installations before that...but it's good to know it for people having similar issues in the future
