### ISSUE TITLE
dependency: imgdistort

### ISSUE THREAD

**Issue by F-Barto** [jpuigcerver/imgdistort#4]
Hello all,

I've successfully installed imgdistort but when executing
`luarocks install https://raw.githubusercontent.com/jpuigcerver/Laia/master/rocks/laia-scm-1.rockspec`

it states:

> Using https://raw.githubusercontent.com/jpuigcerver/Laia/master/rocks/laia-scm-1.rockspec... swi
tching to 'build' mode
>
> Missing dependencies for laia:
> imgdistort
> lbase64
> etlua
> warp-ctc
> lua-term
>
> Error: Could not satisfy dependency: imgdistort

but `sudo make install` in the build directory of imgdistort states:

> [ 33%] Built target affine
> [ 66%] Built target morphology
> [100%] Built target imgdistort
> Install the project...
> -- Install configuration: ""
> -- Up-to-date: /home/barto/torch/install/lib/lua/5.1/libimgdistort.so
> -- Up-to-date: /home/barto/torch/install/share/lua/5.1/imgdistort/init.lua

Anyone know how to fix it?

Regards,

**Comment by jpuigcerver** [comment]
Hi,

Install imgdistort via:

```shell
luarocks install https://raw.githubusercontent.com/jpuigcerver/imgdistort/master/torch/imgdistort-scm-1.rockspec
```

**Comment by F-Barto** [comment]
thank you so much !
